services:
  - type: worker
    name: zenii-x-music
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: LOG_GROUP_ID
        sync: false
